# Generated by Django 4.2.6 on 2023-10-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_usuario_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="fecha_nacimiento",
            field=models.DateTimeField(),
        ),
    ]
