# Generated by Django 4.2.6 on 2023-10-22 04:36

from django.db import migrations
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_usuario_fecha_nacimiento"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", users.managers.CustomUserManager()),
            ],
        ),
    ]
