# Generated by Django 4.2.6 on 2023-10-21 02:09

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("laboratorio", models.CharField(max_length=45)),
                ("nombre", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                ("telefono", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                (
                    "geolocalizacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("online", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("es_medico", models.BooleanField(default=False)),
                ("es_flebotomista", models.BooleanField(default=False)),
                ("es_laboratorio", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("colegiado", models.CharField(max_length=45)),
                ("online", models.BooleanField(default=False)),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "socio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="partners.socio"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
