# Generated by Django 4.2.6 on 2023-10-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="usuario",
        ),
    ]
