# Generated by Django 4.2.6 on 2023-10-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_remove_medico_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="especialidad",
        ),
    ]
