# Generated by Django 4.2.6 on 2023-10-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("orders", "0002_initial"),
        ("partners", "0004_medico_verificado_flebotomista"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaboratorioClinico",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                ("telefono", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name="Laboratorio",
            new_name="SedeLaboratorioClinico",
        ),
    ]
