# Generated by Django 4.2.6 on 2023-10-21 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_laboratorioclinico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sedelaboratorioclinico",
            name="laboratorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partners.laboratorioclinico",
            ),
        ),
    ]
