# Generated by Django 4.2.6 on 2023-10-21 03:19

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_alter_sedelaboratorioclinico_laboratorio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sedelaboratorioclinico",
            name="geolocalizacion",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(-90.513228, 14.642942),
                srid=4326,
            ),
        ),
    ]
