# Generated by Django 4.2.6 on 2023-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=45)),
                ("descripcion", models.CharField(max_length=45)),
            ],
        ),
    ]
