# Generated by Django 4.2.6 on 2023-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicio_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicio",
            name="url",
            field=models.CharField(default="default", max_length=45),
            preserve_default=False,
        ),
    ]
