# Generated by Django 4.2.6 on 2023-11-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_consultamedica_created_at_consultamedica_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
