# Generated by Django 4.2.7 on 2023-11-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicio_sort_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='costo',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='pruebalaboratorio',
            old_name='costo',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='url',
            field=models.CharField(default='/', max_length=45),
            preserve_default=False,
        ),
    ]
