# Generated by Django 4.2.7 on 2023-11-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_rename_costo_consultamedica_precio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='is_active',
            new_name='active',
        ),
    ]
