# Generated by Django 4.2.7 on 2023-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_rename_is_active_consultamedica_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
