# Generated by Django 4.2.7 on 2023-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_consultamedica_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='tiempo_estimado',
            field=models.CharField(default='1 hora', max_length=45),
            preserve_default=False,
        ),
    ]
