# Generated by Django 4.2.6 on 2023-10-21 02:27

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleOrdenLaboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=45)),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("estado", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenConsultaMedica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado_detalle", models.CharField(max_length=45)),
                ("detalles", models.TextField()),
                ("lugar", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                (
                    "geolocalizacion",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(
                            -90.513228, 14.642942
                        ),
                        srid=4326,
                    ),
                ),
                ("paciente_nombre", models.CharField(max_length=45)),
                ("paciente_apellido", models.CharField(max_length=45)),
                ("paciente_edad", models.CharField(max_length=45)),
                ("paciente_dpi", models.CharField(max_length=45)),
                ("paciente_telefono", models.CharField(max_length=45)),
                (
                    "paciente_email",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("paciente_sexo", models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="OrdenPruebaLaboratorio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("estado_detalle", models.CharField(max_length=45)),
                ("lugar", models.CharField(max_length=45)),
                ("direccion", models.CharField(max_length=45)),
                (
                    "geolocalizacion",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(
                            -90.513228, 14.642942
                        ),
                        srid=4326,
                    ),
                ),
                ("paciente_nombre", models.CharField(max_length=45)),
                ("paciente_apellido", models.CharField(max_length=45)),
                ("paciente_edad", models.CharField(max_length=45)),
                ("paciente_dpi", models.CharField(max_length=45)),
                ("paciente_telefono", models.CharField(max_length=45)),
                (
                    "paciente_email",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("paciente_sexo", models.CharField(max_length=1)),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partners.laboratorio",
                    ),
                ),
                (
                    "orden_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orden"
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partners.socio"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroPruebaLaboratorio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comentario", models.TextField(null=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orden"
                    ),
                ),
                (
                    "orden_laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ordenpruebalaboratorio",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partners.socio"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroConsultaMedica",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("motivo", models.TextField(null=True)),
                ("historia", models.TextField(null=True)),
                ("exploracion", models.TextField(null=True)),
                ("diagnostico", models.TextField()),
                ("plan", models.TextField()),
                ("comentario", models.TextField(null=True)),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.orden"
                    ),
                ),
                (
                    "orden_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ordenconsultamedica",
                    ),
                ),
                (
                    "socio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="partners.socio"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
