# Generated by Django 4.2.6 on 2023-10-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroconsultamedica",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="registropruebalaboratorio",
            name="orden",
        ),
    ]
