# Generated by Django 4.2.6 on 2023-10-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicio_is_active"),
        ("orders", "0004_alter_orden_estado_alter_orden_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="services.servicio"
            ),
        ),
    ]
