# Generated by Django 4.2.6 on 2023-10-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_orden_tipo_orden_servicio"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalleordenlaboratorio",
            old_name="catalogo_prueba_laboratorio",
            new_name="prueba_laboratorio",
        ),
    ]
