# Generated by Django 4.2.6 on 2023-10-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0007_rename_catalogo_prueba_laboratorio_detalleordenlaboratorio_prueba_laboratorio",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="registroconsultamedica",
            old_name="orden_consulta",
            new_name="orden_id",
        ),
        migrations.RenameField(
            model_name="registropruebalaboratorio",
            old_name="orden_laboratorio",
            new_name="orden_id",
        ),
        migrations.RemoveField(
            model_name="detalleordenlaboratorio",
            name="orden_laboratorio",
        ),
        migrations.AddField(
            model_name="detalleordenlaboratorio",
            name="orden_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.orden",
            ),
            preserve_default=False,
        ),
    ]
